<?php

namespace AppBundle\Repository;

/**
 * PersoonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersoonRepository extends \Doctrine\ORM\EntityRepository
{
}
