<?php

namespace AppBundle\Repository;

/**
 * VerzoeknummerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerzoeknummerRepository extends \Doctrine\ORM\EntityRepository
{
}
